# Generated by Django 3.0.2 on 2020-01-21 20:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, default='../static/img/default_post.jpg', upload_to='photos/'),
        ),
    ]
