# Generated by Django 3.0.2 on 2020-01-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200126_2229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsletterUser',
            new_name='Subscriber',
        ),
    ]
