# Generated by Django 3.0.2 on 2020-01-21 20:31

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200121_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='photos/'),
        ),
    ]
