# Generated by Django 3.0.2 on 2020-01-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200128_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='date_added',
            field=models.DateField(),
        ),
    ]
